---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-runners
  namespace: actions
spec:
  template:
    spec:
      repository: ashish-sharma-edstem/test-prvate
      labels:
        - my-custom-runner
      env: []
